### ISSUE TITLE
Custom default visualizations

### ISSUE THREAD

**Issue by hmansell** [fsprojects/IfSharp#10]
Loving this - great work guys!

Just wondering whether it is possible to register some custom visualizations for a type.  For example, a Deedle frame?

Right now, if I reference Deedle and create a series I get a textual output.   Would love for the default to be an HTML table for a Series or Frame.

e.g.:

```
open Deedle

series [ 1 => 2; 2 => 3]
```
val it : Series<int,int> = series [ 1 => 2; 2 => 3]

**Comment by sylvanc** [comment]
Closing as custom `Display` printers now work very well :)
