### ISSUE TITLE
kernel dies by creating F# notebook in the Docker

### ISSUE THREAD

**Issue by vilinski** [fsprojects/IfSharp#101]
### Description

unhandled System.Net.Sockets.SocketException by creating an F# notebook.

### Repro steps

I have tried the IfSharp for the first time. Run in the docker and can't get it to work

1.  cloned the github repo

2. Created `docker-compose.yaml` file within repository, just to simplify handling volumes, ports and proxy:
```yaml
version: '2'
volumes:
  notebooks:
services:
  ifsharp:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - '8888:8888'
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ./notebooks:/notebooks:rw
```

3. `docker-compose up`
4. created a new F# notebook in the web UI

### Expected behavior

Have also tried to use Dockerfile based on mono:latest, hoping it is some old mono bug but with the same result.

### Actual behavior

Kernel is for a second connecting, than died and tries to restart

<details><summary> Expand to see the docker container log</summary><p>
> ifsharp_1  | Unhandled Exception:
> ifsharp_1  | System.Net.Sockets.SocketException (0x80004005): Operating system sockets do not support ReuseAddress.
> ifsharp_1  | If your socket is not intended to bind to the same address and port multiple times remove this option, otherwise you should ignore this exception in                                              side a try catch and check that ReuseAddress is true before binding to the same address and port multiple times.
> ifsharp_1  |   at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, Sy                                              stem.Int32 optionValue) [0x0003d] in <bd46d4d4f7964dfa9beea098499ab597>:0
> ifsharp_1  |   at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, Sy                                              stem.Boolean optionValue) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
> ifsharp_1  |   at NetMQ.Core.Utils.Signaler..ctor () [0x0002e] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.Core.Mailbox..ctor (System.String name) [0x00012] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.Core.Ctx..ctor () [0x00035] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.NetMQConfig.get_Context () [0x00017] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.NetMQSocket..ctor (NetMQ.ZmqSocketType socketType, System.String connectionString, NetMQ.NetMQSocket+DefaultAction defaultAction) [0x0000                                              6] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.Sockets.RouterSocket..ctor (System.String connectionString) [0x00000] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at IfSharp.Kernel.IfSharpKernel..ctor (IfSharp.Kernel.ConnectionInformation connectionInformation) [0x00010] in <5837ff451b085d3da745038345ff3758>                                              :0
> ifsharp_1  |   at IfSharp.Kernel.App.Start (System.String[] args) [0x00091] in <5837ff451b085d3da745038345ff3758>:0
> ifsharp_1  |   at IfSharpConsole.Program.Main (System.String[] args) [0x00014] in <8de5c123f2584cda95f2586ac1a23da9>:0
> ifsharp_1  | [ERROR] FATAL UNHANDLED EXCEPTION: System.Net.Sockets.SocketException (0x80004005): Operating system sockets do not support ReuseAddress.
> ifsharp_1  | If your socket is not intended to bind to the same address and port multiple times remove this option, otherwise you should ignore this exception in                                              side a try catch and check that ReuseAddress is true before binding to the same address and port multiple times.
> ifsharp_1  |   at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, Sy                                              stem.Int32 optionValue) [0x0003d] in <bd46d4d4f7964dfa9beea098499ab597>:0
> ifsharp_1  |   at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, Sy                                              stem.Boolean optionValue) [0x0000e] in <bd46d4d4f7964dfa9beea098499ab597>:0
> ifsharp_1  |   at NetMQ.Core.Utils.Signaler..ctor () [0x0002e] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.Core.Mailbox..ctor (System.String name) [0x00012] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.Core.Ctx..ctor () [0x00035] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.NetMQConfig.get_Context () [0x00017] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.NetMQSocket..ctor (NetMQ.ZmqSocketType socketType, System.String connectionString, NetMQ.NetMQSocket+DefaultAction defaultAction) [0x0000                                              6] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at NetMQ.Sockets.RouterSocket..ctor (System.String connectionString) [0x00000] in <3a2aeb94302c42a9990a4beacef5db1a>:0
> ifsharp_1  |   at IfSharp.Kernel.IfSharpKernel..ctor (IfSharp.Kernel.ConnectionInformation 

connectionInformation) [0x00010] in <5837ff451b085d3da745038345ff3758>    
</p></details>

### Known workarounds

No known workarounds.

### Related information 

* Host os is Debian x86_64 behind a proxy
* Docker 1.12.3
* Have also tried to use Dockerfile based on mono:latest, hoping it were some old mono bug, but with the same result.
* What could I have done wrong?

**Comment by cgravill** [comment]
Which version of mono are you using? There is a networking bug in 4.6.* see #90

**Comment by vilinski** [comment]
I'm using the mono version which is defined in the Dockerfile. As mentioned I have also tried mono:latest, which is 4.6.2 now. Is there any reason for not do so?
<details><summary>Dockerfile based on mono:latest</summary>

```Dockerfile
FROM mono:latest

RUN    apt-get update \
    && apt-get install -y \
        python3-pip \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && pip3 install jupyter

WORKDIR /
RUN git clone https://github.com/fsprojects/IfSharp.git

WORKDIR /IfSharp
RUN git checkout jupyter
RUN ./build.sh
RUN mono bin/ifsharp.exe --install

WORKDIR /
RUN mkdir notebooks
VOLUME notebooks

EXPOSE 8888

ENTRYPOINT ["jupyter", \
            "notebook", \
            "--no-browser", \
            "--ip='*'", \
            "--port=8888", \
            "--notebook-dir=/notebooks" \
            ]
```

</details>

**Comment by vilinski** [comment]
Oh, it seems it will be fixed in 4.8 first ...

**Comment by sylvanc** [comment]
I've changed the Dockerfile to use mono 4.4 and the master branch in #102

**Comment by sylvanc** [comment]
Thanks for the report, @vilinski !
