### ISSUE TITLE
Consider renaming to jupyter-fsharp

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#103]
We should consider renaming this repo to fsharp-jupyter or jupyter-fsharp.

**Comment by sylvanc** [comment]
The "I" prefix dates from IPython. Some other kernels:

https://github.com/ipython/ipython
https://github.com/IRkernel/IRkernel
https://github.com/JuliaLang/IJulia.jl
https://github.com/gibiansky/IHaskell

Some are switching however:

https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages

Particularly:

https://github.com/notablemind/jupyter-nodejs
https://github.com/fredokun/cl-jupyter

Or even:

https://github.com/fabian-z/gopherlab

**Comment by cgravill** [comment]
I adjusted the top level description in this direction but left the "I" in placed.

I'm going to close this as dormant, happy to discuss more in the future especially if strong conventions in the Jupyter kernel space emerge.
