### ISSUE TITLE
Export as F# code should include markdown

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#105]
When you choose "Export to .fs" the results should include the markdown.

Ideally we should also include instructions on how to get the necessary ``Util...`` libraries

**Comment by cgravill** [comment]
Agreed. I just checked and Python does export the Markdown into the .py file.

**Comment by cgravill** [comment]
Turns out this is a general problem with languages other than Python: https://github.com/IRkernel/IRkernel/issues/394

Looks feasible to write a module to do this.

**Comment by cgravill** [comment]
Yes, it's possible to create module that exports the markdown commented in F# style.

fsharp.py
```python
"""FSharp script Exporter class"""

from .templateexporter import TemplateExporter

class FSharpExporter(TemplateExporter):
    """
    Exports an F# code file.
    """
    def _file_extension_default(self):
        return '.fs'

    def _template_file_default(self):
        return 'fsharp'

    output_mimetype = 'text/x-fsharp'
```

and a template
```
{%- extends 'null.tpl' -%}

{% block in_prompt %}
// In[{{ cell.execution_count if cell.execution_count else ' ' }}]:
{% endblock in_prompt %}

{% block input %}
{{ cell.source }}
{% endblock input %}

{% block markdowncell scoped %}
{{ cell.source | comment_lines_fsharp }}
{% endblock markdowncell %}
```
Then produces:
```
// In[1]:

[|1;2;3|]
|> Seq.map (fun x -> x*x)

// Test Markdown
// =============
```

However, it looks like the way such exporters are being configured is being improved: https://github.com/jupyter/nbconvert/issues/361 I'm not sure how we'd go about distributing the exporter as is.

**Comment by cgravill** [comment]
The underlying issue for this isn't being worked on and has been closed. So while I agree it's desirable it's unlikely to happen. I'm going to close this, if someone wants to make progress in nbconvert this can be reconsidered.
