### ISSUE TITLE
"null" gets displayed for a "unit" result

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#110]
We print "null" for unit.  We should fix this.  There is a corresponding fir already in F# 4.1, we should integrate it to FSharp.Compier.Service, pick up the new release here, and make sure it's being used

**Comment by cgravill** [comment]
That actually raises an interesting question, we upgraded to F# 4.0 to easily support Paket. However, should we be producing multiple kernels so people can chose F# version? Or just keep fixing on the most recent stable version?

**Comment by cgravill** [comment]
Could you point me to the fix or ticket? That way we can update when this is addressed upstream. I've updated our dependencies but we're still printing `<null>`.

**Comment by sylvanc** [comment]
Fixed in #127
