### ISSUE TITLE
fsi.PrintLength doesn't adjust the displayed print length

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#111]
We should consider using parameters such as ``fsi.PrintLength <- 1000`` to control the print length and depth for displayed values, e.g. [ 1 .. 10000 ].  My son told me "100 vauees is not enough, I want to see the whole lot".

Also we should consider using the floating point formats in the same object.

**Comment by cgravill** [comment]
What's happening is that we're applying `sprintf "%A"` on `<obj>` to the last expression as a default formatter. Is it possible to make that respect the PrintLength setting?

As a workaround, if you add:
```fsharp
#fsioutput "on"
fsi.PrintLength <- 1000

[1..500]
```
then you'll get both outputs, where the first respects PrintLength.

It might be clearest to take explicit control and stringify the collection directly.

**Comment by sylvanc** [comment]
Fixed in #129
