### ISSUE TITLE
Displaying graphs in IfSharp

### ISSUE THREAD

**Issue by mavnn** [fsprojects/IfSharp#117]
### Description

Hi! I'd like to visualize simple graphs (as in, edges and nodes rather than bar charts) in a notebook. At the moment the simplest option looks like a wrapper around D3; it looks like XPlot should be able to do something along those lines but I'm struggling to work out how.

Can anyone point me to some examples?

**Comment by cgravill** [comment]
It's not a graph visualization but there is an example of interacting with D3 from the notebooks at the end of the feature notebook: https://github.com/fsprojects/IfSharp/blob/master/FSharp_Jupyter_Notebooks.ipynb

We use https://github.com/Microsoft/automatic-graph-layout for our graphs which you can then return the result as an image. There's a lot more features in that though.

**Comment by mavnn** [comment]
Thanks! I managed to get something working (you can see it at http://blog.mavnn.co.uk/advent-2016/ ). Tempted to write a little plugin fsx for it; graphs are something I want fairly often in data exploration.
