### ISSUE TITLE
Pretty printing of function types

### ISSUE THREAD

**Issue by fuglede** [fsprojects/IfSharp#125]
This might well be more of a question than an issue report, but this seems like the proper place for it in any case:

In F# Interactive, I can efficiently investigate the types of domains and ranges of functions;

    > let addTwo = (+) 2;;

    val addTwo : (int -> int)

Is there some way to reproduce the `int -> int` part in IfSharp? It does not come out of the box:

     In[1]: let addTwo = (+) 2
            addTwo
    Out[1]: <fun:addTwo@1-10>

You can sort of do a workaround by digging into the type, but this seems a bit nasty in comparison with the above:

     In[2]: addTwo.GetType().BaseType
    Out[2]: Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,System.Int32]

**Comment by cgravill** [comment]
Yes, there's a directive you can enable to also get the F# Interactive output to display

```
let addTwo = (+) 2
addTwo

Out[2]:
<fun:addTwo@1-1>

In [3]:
#help

Out[3]:
  IF# notebook directives:

    #fsioutput ["on"|"off"];;   Toggle output display on/off
    
  F# Interactive directives:

    #r "file.dll";;        Reference (dynamically load) the given DLL
    #I "path";;            Add the given search path for referenced DLLs
    #load "file.fs" ...;;  Load the given file(s) as if compiled and referenced
    #time ["on"|"off"];;   Toggle timing on/off
    #help;;                Display help
    #quit;;                Exit

  F# Interactive command line options:

      See 'ifsharp --help' for options


In [4]:
#fsioutput "on"

In [5]:
addTwo
Out[5]:
val it : (int -> int) = <fun:addTwo@1-1>
Out[5]:
<fun:addTwo@1-1>
```

What we're doing is printing the expression to enable us to have inline graphics. Using the extra fsioutput directive allows you to get back out exactly what the embedded F# Interactive instance is producing.

**Comment by fuglede** [comment]
Excellent, thanks for the info, and apologies for the noise.
