### ISSUE TITLE
IFSharp for Windows 32-bit

### ISSUE THREAD

**Issue by mainul12** [fsprojects/IfSharp#145]
### Description

IFSharp.exe does not run on Windows 32-bit machine. Will there be an edition to enable this in the future?

**Comment by cgravill** [comment]
My understanding is that the 64-bit requirement was to simplify dependencies e.g. ZeroMQ which has been replaced with a pure .net implementation. So it's likely possible to switch to supporting both 32-bit and 64-bit.

I'm not aware of any plans to actually do it but pull requests are welcome.

**Comment by cgravill** [comment]
I'm going to close this for now but happy to take a pull request to make it work on both 32bit and 64bit.
