### ISSUE TITLE
When using #N preprocessor the cells execution does not finish

### ISSUE THREAD

**Issue by frelon** [fsprojects/IfSharp#161]
### Description

It's just a small side note, but when using the #N preprocessor the cell status will show as running instead of an error/ok status

### Repro steps

Please provide the steps required to reproduce the problem

Add a cell with #n "FsLab" and execute it

### Expected behavior

End execution as error or ok?

### Actual behavior

Shows running status [*]

### Known workarounds

Restarting the kernel removes the status

**Comment by cgravill** [comment]
Fixed by @frelon on #164 thanks!
