### ISSUE TITLE
Automatically reference NuGet dependencies

### ISSUE THREAD

**Issue by mndrake** [fsprojects/IfSharp#17]
I don't know how easy this would be to include, but I was hoping it would be possible to mimic the default behavior for the Visual Studio NuGet Package Manager.  If you reference a packaged via ``#N`` the dependencies are not retrieved if not already downloaded.  An example that has a few layers of dependencies would be ``#N "FsLab/0.0.13-beta"``.

**Comment by sylvanc** [comment]
We've moved to `paket` in the `jupyter` branch, and away from automatic assembly resolution.
