### ISSUE TITLE
Incorrect error messages 

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/IfSharp#173]
I tried several issues, all they remain obfuscated to me, while other .Net online editors show it precisely:

![img_20180316_144253](https://user-images.githubusercontent.com/6344099/37524006-e34d0be2-2928-11e8-90e7-c90b71fa358b.png)

![img_20180316_144327](https://user-images.githubusercontent.com/6344099/37524012-e7ea4ed0-2928-11e8-9b71-508f00d86810.png)

**Comment by cgravill** [comment]
Looks to work for me:

![image](https://user-images.githubusercontent.com/1099725/37525212-1f664238-2924-11e8-8967-3fb1e6079978.png)

Could you share your Azure Notebook? Perhaps something else is wrong there.

**Comment by ShalokShalom** [comment]
https://fsharp-shalokshalom.notebooks.azure.com/nb/notebooks/TestNotebook.ipynb

**Comment by cgravill** [comment]
That's very strange, with your notebook I see the same fairly helpful error message. It looks as if you're somehow running a different version of IfSharp than I am locally or on Azure Notebooks.

Did you recently create the notebook? Have you been using Azure Notebooks for awhile?

@crwilcox any idea how this might be happening? Should we raise this on https://github.com/Microsoft/AzureNotebooks/ ?

**Comment by ShalokShalom** [comment]
Yes, recently and on a new account.

**Comment by ShalokShalom** [comment]
Does it make a difference if I created this account and Notebook with a slightly outdated browser?

**Comment by cgravill** [comment]
Not that I'm aware of. It would be good to try another current browser as a test if you have one available.

I've seen this sort of usage work happily on Edge, Chrome, Firefox, and Safari.

**Comment by ShalokShalom** [comment]
It works now fine in a current browser (on the desktop) so I see this as solved, thank a lot.
