### ISSUE TITLE
NullReferenceExceptionObject on memory limit

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/IfSharp#174]
The complete code:

```fsharp
let x = 42

x + 3

let greet name = 
    printfn "Hello, %s" name

open System
open System.IO

let path = "/home/nbuser/trainingsample.csv"
let data0 = File.ReadAllLines path

let data1 = 
    data0 
    |> Array.map (fun line -> line.Split(','))

data0.[1..50] |> Array.map (fun (line:string) -> line.Split(','))
```

See here the working case:

![screenshot_20180412_203637](https://user-images.githubusercontent.com/6344099/38697773-3791657a-3e93-11e8-9e09-52aab984d685.png)

Change data0.[1..10] into a higher value like [1..50] and you get the following error:

![screenshot_20180412_203924](https://user-images.githubusercontent.com/6344099/38697786-3e2df42a-3e93-11e8-9703-4b75c017cd5e.png)

Full Error here:
https://gist.github.com/ShalokShalom/84c4d8a488925189fd9a99ffc09ca7fd

And here is the used trainingsample.csv. 
Right click on `View Raw` OR `Download` and then on `Save Link/Target as..` in order to download it.

https://github.com/c4fsharp/Dojo-Digits-Recognizer/blob/master/Dojo/trainingsample.csv

**Comment by cgravill** [comment]
Looks like another instance of #143 on Mono.

**Comment by ShalokShalom** [comment]
Yeah, might be. So this can be closed? Do you consider a switch to dotnetcore?

**Comment by cgravill** [comment]
Sure, happy either way on closing. There's a self-contained test case on the other issue but once fixed it would be good to have people confirm.

I'd really like to get it fixed on Mono but haven't found anyone experienced with Mono debugging and available to help so far.

I'm also really interested in a dotnetcore build - I've started experimenting on other projects and it looks good. The challenge with something like the notebooks is compatibility, it might be a bit soon in the ecosystem to move over. The first step would be to check if everything in paket.dependencies has a dotnetcore build then could see about a test build.
