### ISSUE TITLE
For Plotly chart library implement make_subplots functionality

### ISSUE THREAD

**Issue by AndreiDegtiarev** [fsprojects/IfSharp#186]
In comparison to IPython the subplots functionality I'm missing mostly in IfSharp
Target behavior see [https://plot.ly/python/subplots/](https://plot.ly/python/subplots/)

**Comment by cgravill** [comment]
Subplots would be great. In Python is this that implemented by IPython or the underlying libraries? I'm wondering if the right place for this is in XPlot instead. There's a issue that looks relevant:

https://github.com/fslaborg/XPlot/issues/49

**Comment by AndreiDegtiarev** [comment]
You are right, it seems that the issue [fslaborg/XPlot#49](https://github.com/fslaborg/XPlot/issues/49) describes the same feature, except that I’m quite sure, that this feature doesn’t exist at all. Some steps towards subplots functionality were already done: see Chart.ShowAll. But in my case this function just opens a new tab in the browser and doesn’t not plot charts directly in the notebook. Do you think that it is possible to correct this behavior?

**Comment by cgravill** [comment]
Yes, my guess is you'd need to do something like the linked issue. Rather than ShowAll you want to construct a single figure like is done in the Python. Then IfSharp will be able to display it. If ShowAll does what you need but pushes the result to the wrong place there decent change XPlot can be adjusted to get what you're after.

**Comment by cgravill** [comment]
I'm going to close this issue, it's an important feature but it's external to IF#. If it's implemented in XPlot happy to take any support changes to the helper scripts here.
