### ISSUE TITLE
MathJax not displayed on Print Preview and Download as HTML when used with XPlot.Plotly

### ISSUE THREAD

**Issue by cannorin** [fsprojects/IfSharp#195]
### Description

~~LaTeX equations `$..$` inside Markdown blocks are rendered in the notebook with MathJax, but not in the print preview and the downloaded HTML.~~

**When used with `XPlot.Plotly.fsx`**, LaTeX equations `$..$` inside Markdown blocks are rendered in the notebook with MathJax, but not in the print preview and the downloaded HTML.

### Repro steps

1. Change the cell to Markdown

2. Enter any LaTeX equation such as `$1+2$`

~~3. Execute File>Print Preview~~

3. **Use `#load "XPlot.Plotly.fsx`**

4. Execute File>Print Preview

### Expected behavior

The equation will get rendered.

### Actual behavior

`$1+2$` is shown as-is.

### Known workarounds

~~Not known.~~

Print the notebook directly to a PDF with the browser.

### Related information 

* Operating system: Debian GNU/Linux buster/sid
* Branch: Release 3.0.0
* .NET Runtime, CoreCLR or Mono Version:
```
$ mono --version
Mono JIT compiler version 5.18.0.225 (tarball Wed Jan  2 21:21:16 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
$ dotnet --version
2.2.102
```

**Comment by cgravill** [comment]
I've tried this in a couple of places and print preview seems to be working for me:

![image](https://user-images.githubusercontent.com/1099725/51379897-6a61e680-1b08-11e9-9bec-d3faea98d09f.png)

It's behaving right on Edge / Windows 10 and Safari / macOS.

Does LaTeX work correctly for you in a Python notebook when you download the html?

**Comment by cannorin** [comment]
@cgravill It seems not to be the simplest repro.
![screenshot from 2019-01-18 19-58-26](https://user-images.githubusercontent.com/13620400/51382978-86db3e80-1b5b-11e9-8d7c-9deacf35a2a1.png)
![screenshot from 2019-01-18 20-00-52](https://user-images.githubusercontent.com/13620400/51383156-fc470f00-1b5b-11e9-80e1-24c7bce86c46.png)

It turned out that the `XPlot.Plotly.fsx` is actually causing the problem:
![screenshot from 2019-01-18 20-09-28](https://user-images.githubusercontent.com/13620400/51383512-fbfb4380-1b5c-11e9-83b9-1f3c7202fac2.png)

Sorry for confusing you.

**Comment by cannorin** [comment]
I've updated the issue accordingly.

**Comment by cgravill** [comment]
Ah it's probably this then:
https://github.com/plotly/plotly.py/issues/515

**Comment by cannorin** [comment]
Ahh so is it not related to IFSharp? Sorry if so...

**Comment by cgravill** [comment]
It's in-between. The way, and others, load XPlot/Plotly looks like it's causing the issue. It looks like they have a new flag that might help us. Needs investigating.

**Comment by cgravill** [comment]
I found a potential workaround for this of hiding MathJax (used for LaTeX) from Plotly so it won't mangle it. It follows on from what I did with @npmurphy who originally integrated XPlot into IFSharp. It works in the notebook and on print preview for me:

![image](https://user-images.githubusercontent.com/1099725/51445206-79a88600-1cfa-11e9-83ce-49d05a3c50a3.png)

@cannorin if you get a chance could you confirm if works for you? It's on pull request #196 

I also updated XPlot.Plotly and Plotly JavaScript to their latest stable version so will need to do a bit more testing elsewhere too.

**Comment by cannorin** [comment]
@cgravill Thanks! I'll try later today.

**Comment by cgravill** [comment]
Great, thanks for testing. It looked good on my other tests too so I'll go ahead and merge.

On the F# highlighting, I don't think F# highlighting on print preview has ever worked. It's probably falling back on styling it as Python. Last time I looked into this sort of thing on #105 while I easily adjusted export the templates needed configuring inside the Python distribution. That seemed messy so it's been on hold until changes are made upstream or someone comes up with a good approach.

**Comment by cannorin** [comment]
Thank you! Now I'll close this issue as solved.

Hmm... It looks really complicated. I think I might be able to override it with something like highlight.js. It's just an idea and will be a dirty workaround, though. Anyway, thanks for fixing this!
