### ISSUE TITLE
IF# freezes after plotting in external window with RProvider

### ISSUE THREAD

**Issue by smoses2** [fsprojects/IfSharp#215]
I am working through Mathias Brandewinder's "Machine Learning Projects" book  using IF#.  When I call the R.hist() as below, I do get the chart to display in an external window, but the top of the chart window reads "Unresponsive", and IF# locks up and needs to be closed down and restarted.  

#load "Paket.fsx"
Paket.Version [ "FSharp.Data", "3.0.1"
                         "RProvider", "1.1.22"]
#load "Paket.Generated.Refs.fsx"
open FSharp.Data
open RProvider
open RProvider.``base``
open RProvider.graphics

R.hist([10;20;30])

I am running Windows 10 with Anaconda installed R.  Is there a way to get the R plot to display inline (preferred) or in an external window without a crash?

**Comment by cgravill** [comment]
Ah nice book! I made notebooks of some parts of it during a workshop with Mathias.

There are lots of options, one is you can render to an image rather than an interactive window. A quick 
and messy version:

`Ensure you've installed a compatible version of R first. 3.4.4 worked for me https://cran.r-project.org/bin/windows/base/old/3.4.4/`

```fsharp
#load "Paket.fsx"
Paket.Version [
    "FSharp.Data", "3.0.1"
    "RProvider", "1.1.22"]
#load "Paket.Generated.Refs.fsx"
```
```fsharp
open FSharp.Data
open RProvider
open RProvider.``base``
open RProvider.graphics
open RProvider.grDevices
```
```fsharp
let temporaryFilename = System.IO.Path.GetTempFileName()
R.png(filename=temporaryFilename, height=400, width=700, bg="white") //New rendering context
R.hist([10;20;30]) //Do the actual drawing
R.dev_off () // Close the device
```

```fsharp
Util.Image(temporaryFilename)
```
![image](https://user-images.githubusercontent.com/1099725/56150946-fc627980-5fa7-11e9-854e-1e1f6991b269.png)

**Comment by smoses2** [comment]
That is great Colin.  I'll give that a try.  

I'm also attending an NDC Workshop with Mathias in May.

**Comment by cgravill** [comment]
Glad it helped, Mathias has a new talk on modelling complex systems (D&D) in F# that I really enjoyed too

**Comment by cgravill** [comment]
@dsyme this a good example of our discussion about where the code between IF# and libraries should exist. While the above works (for me at least) then it's quite fiddly. I saw you're trying to revitalise R in .net and it's the kind of thing that makes a lot of sense in a notebook context.

We could add a helper .fsx for R in notebooks but maintaining that for every possible library is a lot of responsibility and might apply to other environments. Thoughts?

**Comment by smoses2** [comment]
@cgravill - thanks again. Had a chance to finally try your code fix and it worked perfectly for both R plotting and for FSharp.Charting (piped to Chart.Save).  Really appreciate the help - without inline plots, would be tougher to use F# notebooks as a python or R-based notebook replacement.

 Do I need to release resources/close device with FSharp.Charting as you did for the R plotting with R.dev_off?

**Comment by cgravill** [comment]
Great, glad it helped R via a type provider is a pretty nice match for notebooks.

You shouldn't generally need to be so explicit about resources - I don't know why it's needed in this case with R but I found the solution in https://fslab.org/RProvider/Charts-QuickStart.html It might be worth raising the question about api over there.

If what you're doing with FSharp.Charting is working that's great and I wouldn't worry about it.

btw there are a few other plotting options as well, see the feature notebook (https://github.com/fsprojects/IfSharp/blob/master/FSharp_Jupyter_Notebooks.ipynb). A lot of people use XPlot at the moment but there are several supported options.
