### ISSUE TITLE
Docker build failing on "GenerateDepFiles"

### ISSUE THREAD

**Issue by zakaluka** [fsprojects/IfSharp#217]
### Description

The docker build is failing on step 29, due to an unexpected error when executing `GenerateDepFiles`.

### Repro steps

1. Clone repo

2. docker build .

### Expected behavior

Docker build succeeds.

### Actual behavior

Docker build fails on step 29.

### Known workarounds

dotnet/core#2540

### Related information 

* Operating system: Windows 10
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: Mono 5.20 base, .NET Core 2.2
* Performance information, links to performance testing scripts

**Comment by zakaluka** [comment]
PR to correct issue: #216

**Comment by cgravill** [comment]
Thanks for applying the workaround
