### ISSUE TITLE
.NET Core : The type 'Stopwatch' is not defined in 'System.Diagnostics'.

### ISSUE THREAD

**Issue by fradav** [fsprojects/IfSharp#227]
### Description

Some standard library routines aren't available
like `System.Diagnostics.StopWatch()` 
no problem via `fsi.exe`

### Repro steps

```shell
$ git clone https://github.com/fsprojects/IfSharp.git
$ dotnet build -c Release IfSharpNetCore.sln
$ dotnet src/IfSharpNetCore/bin/x64/Release/netcoreapp2.2/IfSharpNetCore.dll
``` 
Open a new fsharp notebook
and type in a cell :
```fsharp
let timer = new System.Diagnostics.Stopwatch()
```

### Expected behavior

Same as fsi.exe :

```plain
$ dotnet /opt/dotnet/sdk/2.2.105/FSharp/fsi.exe

Microsoft (R) F# Interactive version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let timer = new System.Diagnostics.Stopwatch();;
val timer : System.Diagnostics.Stopwatch
```

### Actual behavior

![image](https://user-images.githubusercontent.com/701587/59037966-98a35100-8872-11e9-8c69-9d39d5cdeb43.png)

### Known workarounds

None

### Related information 

* Archlinux up-to-date
* dotnet sdk 2.2.105

**Comment by cgravill** [comment]
I get the same on Windows. The hosted fsi instance appears not to have the default opens.

As a workaround you can do this:

```fsharp
#r "System.Runtime.Extensions.dll"
```
![image](https://user-images.githubusercontent.com/1099725/59092678-123a4e00-890a-11e9-91f2-088258d5d60a.png)

We should probably figure out what fsi is default opening and do the same for the .NET Core version.

**Comment by fradav** [comment]
Ok it works with this, thanks.

**Comment by cgravill** [comment]
Great, glad that helped.

Before we release/stabilise the .NET Core version we should figure out why it behaves differently. Probably some configuration difference between F# Compiler Service hosted FSI and the local build of fsi.
