### ISSUE TITLE
dotnet core not generating "Paket.Generated.Refs.fsx"

### ISSUE THREAD

**Issue by rudihorn** [fsprojects/IfSharp#232]
### Description

If I understand the sample correctly, using `Paket.Package` should generate a file called `Paket.Generated.Refs.fsx`, which is then loaded using `#load "Paket.Generated.Refs.fsx`. I could not find this file.

### Repro steps

Taken from the sample:
```F#
#load "Paket.fsx"
```

```
Paket.Package ["Angara.Table"; "Angara.Statistics"]
```

```
#load "Paket.Generated.Refs.fsx"
```

### Expected behavior

No error message.

### Actual behavior

>Unable to find the file 'Paket.Generated.Refs.fsx' in any of
 /home/jupyter/IfSharp/src/IfSharpNetCore/bin/release/netcoreapp2.2
 /home/jupyter/jupyter-data

### Known workarounds

Load packages using explicit path, e.g.

```
#load ".paket/load/netstandard2.0/Angara.Table.fsx"
#load ".paket/load/netstandard2.0/Angara.Charting.fsx"
```

### Related information 

* Operating system: Ubuntu
* Master
* CoreCLR

**Comment by cgravill** [comment]
Just fixed and pushed, it wasn't set to copy in this version.

**Comment by rudihorn** [comment]
Thanks!
