### ISSUE TITLE
MyBinder

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/IfSharp#234]
This here could be in your interest, just close it once read. :hugs: 

https://gke.mybinder.org

**Comment by cgravill** [comment]
I've seen Binder before with Python, does it work with F#?

**Comment by ShalokShalom** [comment]
Yeah, it is language agnostic:

https://mybinder.readthedocs.io/en/latest/using.html#choose-from-many-open-source-languages

**Comment by cgravill** [comment]
I wasn't sure about is the set of commands needed:
https://mybinder.readthedocs.io/en/latest/howto/languages.html#languages-not-covered-here

If it's documented I'd be happy to see it included in the documentation so people can use Binder with F#.

**Comment by agoose77** [comment]
All you need to do is use the `start` and `postBuild` bash files to configure the instance (see https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder)

In this case, you would install `IfSharp` using bash commands in `postBuild`, and do anything related to the environment (e.g sourcing env variables) in `start`
