### ISSUE TITLE
Document the supported fsharp release

### ISSUE THREAD

**Issue by ShalokShalom** [fsprojects/IfSharp#235]
Which release is currently supported?

The docu says 4.1 is tested, while this says nothing about the compatibility, or?

:hugs:

**Comment by cgravill** [comment]
Anything fairly recent is likely to work.

Probably the more interesting question is the F# Compiler Services version which is documented here:
https://github.com/fsprojects/IfSharp/blob/master/paket.lock
(that's interesting as it affects code entered in the notebook)

We're a couple of versions behind https://www.nuget.org/packages/FSharp.Compiler.Service/ and should update but I'm not aware of anything urgent in those.

**Comment by ShalokShalom** [comment]
Do you know why Azure stops at 4.1: https://github.com/microsoft/AzureNotebooks/issues/709

**Comment by cgravill** [comment]
They haven't updated their version of IfSharp in a while.

**Comment by ShalokShalom** [comment]
Oh I see. Is this a huge undertaking on their side?

**Comment by cgravill** [comment]
I don't know. I sometimes help the Azure Notebooks team out on issues relating to the F# support but I'm not directly in the chain of their deployment pipeline.

Happy to help as it's useful - it's great having a such a hosted service, especially e.g. the experiments into GPU hardware https://github.com/Microsoft/AzureNotebooks/wiki/Azure-Notebooks-at-Microsoft-Connect()-2018#connect-notebooks-to-your-own-azure-compute

**Comment by ShalokShalom** [comment]
Yeah, I totally agree on that.
