### ISSUE TITLE
New release with FSharpCore 4.7

### ISSUE THREAD

**Issue by kar8nga** [fsprojects/IfSharp#248]
The [last release](https://github.com/fsprojects/IfSharp/releases/tag/v3.0.3) of ifsharp bundles FSharpCore 4.6.

The last release of VS 16.4 bundles FSharpCore 4.7 [release](https://github.com/dotnet/fsharp/releases/tag/Visual-Studio-2019-Version-16.4). This is the default for new fsharp projects.

Could you make a new release? I see that version 4.7 is already integrated in ifsharp [log](https://github.com/fsprojects/IfSharp/compare/v3.0.3...master).

**Comment by cgravill** [comment]
Certainly, I've just released v3.0.4 with the F# 4.7 update. Hope this helps.

**Comment by cgravill** [comment]
I'll close this for now, but let us know if any adjustments needed

**Comment by kar8nga** [comment]
Thanks for the release. Helps a lot. Sorry, for the late answer, but covid19-induced changes made the last days busy.
