### ISSUE TITLE
Linux installation not working

### ISSUE THREAD

**Issue by CptnCrumble** [fsprojects/IfSharp#250]
### Description

For installation on Lubuntu, installation step 3 (mono ifsharp.exe) throws an exception.

### Repro steps

Followed instructions on README

### Expected behavior

Installation, fire up jupyter notebook

### Actual behavior
Error message:
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### Known workarounds

None

### Related information 

* Operating system - Lubuntu 19.04
* Branch - Master
* .NET Runtime, CoreCLR or Mono Version - 5.18

**Comment by cgravill** [comment]
Have you tried building from source? I'm not aware of anyone having run on Lubuntu before but I'd guess it should behave similarly to Ubuntu.

**Comment by cgravill** [comment]
Also which version of Mono do you have and how did you install? Looks like a related problem here:

https://github.com/mono/mono/issues/17148

I always install mono-complete when using Mono as I'm going to be doing development anyway.

**Comment by CptnCrumble** [comment]
Reinstalled mono (complete), did the trick :+1:

**Comment by cgravill** [comment]
Great, glad it's working. I've updated the install instructions to recommend mono-complete
