### ISSUE TITLE
Doesn't start on MacOS BigSur / dotnet 5.0.100-rc.2.20479.15

### ISSUE THREAD

**Issue by thomasd3** [fsprojects/IfSharp#258]
### Description

Jupyter doesn't start on MacOS BigSur

### Repro steps

type: mono ifsharp.exe

### Expected behavior

I'm expecting jupyter  to start and open the browser

### Actual behavior

I get this output:

```
(base) ~/Downloads/IfSharp.v3.0.4 ᐅ mono ifsharp.exe
Force install required, performing install...
Saving fsharp css [/Users/thomas/Library/jupyter/kernels/ifsharp/static/custom/fsharp.css]
Saving kernel js [/Users/thomas/Library/jupyter/kernels/ifsharp/kernel.js]
Saving webintellisense js [/Users/thomas/Library/jupyter/kernels/ifsharp/static/custom/webintellisense.js]
Saving webintellisense-codemirror js [/Users/thomas/Library/jupyter/kernels/ifsharp/static/custom/webintellisense-codemirror.js]
Saving custom kernel.json file [/Users/thomas/Library/jupyter/kernels/ifsharp/kernel.json]
Saving kernel icon [/Users/thomas/Library/jupyter/kernels/ifsharp/logo-64x64.png]
Saving kernel icon [/Users/thomas/Library/jupyter/kernels/ifsharp/logo-32x32.png]
Installing dependencies via Paket
Starting Jupyter...

```

but then nothing happens

I can type 'jupyter lab' or 'jupyter notebook' and they both start without problem.

There is nothing in the console. How can I get more log info about what's happening?

**Comment by cgravill** [comment]
I'm not sure any has tried Big Sur / macOS 11.x but I'm not aware of anything that would specifically break. My Mac is too old to test on that unfortunately.

If you build from source and run under a debugger you might get more interesting information.
