### ISSUE TITLE
Jupyter / IPython 3.0 version

### ISSUE THREAD

**Issue by mndrake** [fsprojects/IfSharp#35]
For Anaconda the latest version of IPython is 3.0.  I tried using IfSharp and was sucessful in getting cells to evaluate with the IfSharp kernel, but intellisense/code completion does not work. I do not know how much work it is to get this project upgraded, but thought I should submit a placeholder issue.

Dave

**Comment by rgbkrk** [comment]
:+1:

**Comment by mndrake** [comment]
I was able to get fsharp to show up as a kernel option in jupyter by creating the file:  
``%programdata%\jupyter\kernels\ifsharp\kernel.json``  
with the content:  

``{
 "display_name": "fsharp", 
 "language": "fsharp", 
 "argv": [
  "C:\\Program Files\\BayardRock\\IFSharp\\ifsharp.exe",
  "{connection_file}"
 ]
}``

Though when I actually try using the kernel I get:

``[C 15:09:42.641 NotebookApp] Malformed message: ['<IDS|MSG>', '', '{"msg
bde8ba-936b-4999-9645-75d723fd45e9","username":"username","session":"EA1
B4FFD8F56A1AA7C0FE834","msg_type":"kernel_info_reply"}', '{"msg_id":"2EE
243478F629D507D816351","username":"username","session":"EA1177A7444B4FFD
7C0FE834","msg_type":"kernel_info_request"}', '{}', '{"protocol_version"
ipython_version":null,"language_version":[1,0,0],"language":"fsharp"}']``

Maybe someone with more knowledge of ``zmq`` will know what changes are needed to get the messaging between IPython 3 and the IfSharp kernel working.

**Comment by jjkane** [comment]
I have been unable to get Jupyter to recognize the F# kernel. If I use `IFSharp.exe` or `ipython notebook --profile ifsharp`, Jupyter opens; but on a new notebook "kernel dead" is marked. The only kernel on the list is "Python 3", but clicking that does nothing. The command window reads:
```
 [I 08:29:17.876 NotebookApp] Using existing profile dir: 'C:\\Users\\jkane\\.ipython\\profile_ifsharp'
[I 08:29:17.892 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 08:29:17.939 NotebookApp] Serving notebooks from local directory: C:\Users\jkane\Documents\IFSharpNotebooks
[I 08:29:17.939 NotebookApp] 0 active kernels
[I 08:29:17.939 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 08:29:17.939 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
C:\Anaconda3\lib\site-packages\IPython\kernel\manager.py:95: UserWarning: Setting kernel_cmd is deprecated, use kernel_spec to start
 different kernels.
  warnings.warn("Setting kernel_cmd is deprecated, use kernel_spec to "
[E 08:29:28.688 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 407, in __get__
        value = obj._trait_values[self.name]
    KeyError: 'session'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 1247, in validate
        return bytes(value)
    TypeError: string argument without an encoding

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\IPython\html\base\handlers.py", line 365, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Anaconda3\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "C:\Anaconda3\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "C:\Anaconda3\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
        kernel_name=kernel_name, **kwargs)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\manager.py", line 224, in start_kernel
        self.write_connection_file()
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\connect.py", line 488, in write_connection_file
        transport=self.transport, ip=self.ip, key=self.session.key,
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 412, in __get__
        value = method()
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\connect.py", line 438, in _session_default
        return Session(parent=self)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\zmq\session.py", line 430, in __init__
        super(Session, self).__init__(**kwargs)
      File "C:\Anaconda3\lib\site-packages\IPython\config\configurable.py", line 80, in __init__
        self.config = config
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 445, in __set__
        obj._notify_trait(self.name, old_value, new_value)
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 602, in _notify_trait
        c(name, old_value, new_value)
      File "C:\Anaconda3\lib\site-packages\IPython\config\configurable.py", line 159, in _config_changed
        self._load_config(new, traits=traits, section_names=section_names)
      File "C:\Anaconda3\lib\site-packages\IPython\config\configurable.py", line 143, in _load_config
        setattr(self, name, deepcopy(config_value))
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 430, in __set__
        new_value = self._validate(obj, value)
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 451, in _validate
        return self.validate(obj, value)
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 1249, in validate
        self.error(obj, value)
      File "C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py", line 480, in error
        raise TraitError(e)
    IPython.utils.traitlets.TraitError: The 'key' trait of a Session instance must be a bytes object, but a value of '' <class 'str'
> was specified.
[E 08:29:28.766 NotebookApp] {
      "Content-Length": "60",
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.8",
      "Host": "localhost:8888",
      "Referer": "http://localhost:8888/notebooks/Untitled1.ipynb",
      "Origin": "http://localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36",

      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest"
    }
[E 08:29:28.784 NotebookApp] 500 POST /api/sessions (::1) 137.80ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
```
I tried adding a kernel.json file (per a previous comment); but that did nothing.

**Comment by prosconi** [comment]
In 3.0 they changed the API spec slightly is some instances... looking into this

**Comment by prosconi** [comment]
There seems to be significant changes in back-end and front-end.

I think it is best to make a new repo with 3.0+ support and keep this one around for 1.0 and 2.0.

**Comment by mndrake** [comment]
@prosconi I see what you mean it appears there were multiple changes in the [5.0 messaging spec](https://ipython.org/ipython-doc/dev/development/messaging.html) that is used in Python 3.0. Do you want to open a new repo, or would starting a 3.0 branch of this repo be sufficient? Would like to help as time allows. Would be nice to have a 3.0 F# kernel that allowed switching between F#, python, and R.

**Comment by prosconi** [comment]
Not only the backend stuff has changed, but the front-end hooks I used also have changed.

**Comment by npmurphy** [comment]
Just setting a version number allows the existing kernel to work with ipython/juypter 3.1 
https://github.com/BayardRock/IfSharp/pull/38

**Comment by mndrake** [comment]
If anyone is interested I created a [fork](https://github.com/mndrake/IfSharp/tree/jupyter) that uses the 5.0 messaging protocol (python 3.x). There appears to be many changes to IPython that allow for more front end integration through just the kernel and the messaging protocol.  

I would like to get F# working as a pure kernel without the front end hooks so I could use it on a polyglot jupyter server (linux). That being said I want a cross platform (OS X (mono) / Linux (mono) / Windows (.Net)) solution and not just a Linux solution.

What's working:
- code execution
- code completion

What changed from base for cross platform usage:
- uses NetMQ instead of fszmq
- when installed checks to see if running on mono and adjusts `kernel.json` file
- removal of `FSharp.Charting`, might replace with javascript library
- changed to .Net/Mono 4.5 

Other changes:
- uses 5.0 messaging protocol
- removal of front end custom css and js files (want to be able to run with default profile)

It is just a draft, and I don't know if there is similar interest out there. This might appear as a step backwards, since it removes the great intellisense and linting work that has been done. I would hope though that most of it can be reimplemented through the 5.0 messaging framework over time.  

If there is interest and this fork gets a bit more developed It would be nice to have this either as a fork of IfSharp or possibly a project under https://github.com/fsharp.

**Comment by mndrake** [comment]
Additional note:

I'm cheating by starting IPython with `ipython notebook --Session.key=''`. I still need to implement the HMAC signing.

**Comment by prosconi** [comment]
@mndrake Have you seen this: http://tahahachana.github.io/XPlot/ ?

**Comment by mndrake** [comment]
@prosconi I have seen that library in the past. I'll take a look at it again though. That library uses google plots and plot.ly. For work I cannot use anything that uses plot.ly since you are sending your data to plot.ly and their service is rendering the result. I believe that the google api might be similar.  

There are also js libraries that have restrictions around commercial use like highcharts. You have it setup that all one needs to generate is valid html to have it render in IfSharp. I included a wrapper around [metricsgraphics.js](http://metricsgraphicsjs.org/) in my fork for basic charting.  

I believe that the current path of visualization is html/js, that being said though svg files generated by `FSharp.Charting` are nice and compact. It would be nice if there was a cross platform solution for creating plots that generated svg files.

__Draft of js based wrapper module for charting__
https://github.com/mndrake/IfSharp/blob/jupyter/src/IfSharp/Charting.fs
__Example charts__
http://nbviewer.ipython.org/gist/mndrake/f2fbb2c824af6d441549

**Comment by npmurphy** [comment]
@mndrake In case it is useful the HMAC signing might look something like this https://github.com/npmurphy/IfSharp/commit/b7ced9a4b77ae5abea9dd630a19de92c3e70a4e3
Since the kernel works without a key I didn't pursue it.

**Comment by simra** [comment]
Do I need to do anything special when building the fork, to point at NetMQ? I checked out the fork, built it, and updated configs, but the kernel continues to crash trying to load libzmq:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libzmq': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at fszmq.C.zmq_ctx_new()
   at fszmq.Context..ctor()
   at IfSharp.Kernel.App.Start$cont@228(String[] args, Unit unitVar) in c:\GitHub\IFSharp_3\src\IfSharp.Kernel\App.fs:line 236
   at IfSharpConsole.Program.Main(String[] args) in c:\GitHub\IFSharp_3\src\IfSharpConsole\Program.cs:line 10
[I 16:00:38.039 NotebookApp] Interrupted...
[I 16:00:38.039 NotebookApp] Shutting down kernels
[I 16:00:38.039 NotebookApp] Kernel shutdown: 096db88e-9ab5-4680-a1a3-3ea1a44821aa
```

**Comment by mndrake** [comment]
@simra Based on the error message it appears that you built the main branch and not the jupyter branch I linked above.

**Comment by simra** [comment]
Thanks, my mistake.  After building the right branch I run into a different exception which I've isolated to FSharp.Compiler.Service loading fsi.exe.  I've documented the issue [here](https://github.com/fsharp/FSharp.Compiler.Service/issues/364).

**Comment by mndrake** [comment]
I believe that this page (https://fsharp.github.io/FSharp.Compiler.Service/corelib.html) describes the issue. I combined the F#/C# projects in the main project into a single F# command line app and didn't bring over the FSI.exe, FSharp.Core.sigdata/optdata that were in the original project. It worked just fine when I compiled and ran on OS X & Linux. I foolishly made the assumption that if it worked on everything but Windows it would work on Windows. I'll undo the changes and point to an embeded FSharp/FSI, and it's good to now know why it was there.

**Comment by mndrake** [comment]
@simra I switched to the nuget FSharp.Core and included the .sigdata and .optdata files in the project similar to the master branch in the jupyter branch. I only tested on OS X, but hopefully it will now build successfully on Windows.

**Comment by fradav** [comment]
@mndrake 
- Add `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` in the project to solve conflicts between used assemblies
- 4.5 Target framework is incompatible with the Fsharp 3.1,2, has to be upgraded to 4.5.1 target at least
- there is a small bug in your D3 Chart generator for parametric curves:

`Chart.Line [ for i in 0.0 .. 0.02 .. 2.0 * Math.PI -> (sin i, cos i * sin i) ]`
gives
![image](https://cloud.githubusercontent.com/assets/701587/8567381/41146eca-2565-11e5-8ebb-cdf74058c099.png)
instead of something like
![image](https://cloud.githubusercontent.com/assets/701587/8567409/71d89950-2565-11e5-86ab-7797e5eea991.png)

**Comment by mndrake** [comment]
I haven't dug into the issue too much, but I'm guessing that that somewhere in the `*.js` libraries it is sorting the data. I guess it makes sense since the library (metrographics.js) appears to be primarily a time series focused library. I was able to reproduce the issue with a simple example (http://jsfiddle.net/mndrake/hk63jfg3/12/). I wonder if there is another easy to use javascript libary that doesn't have this behavior that could be used instead?

**Comment by mndrake** [comment]
Maybe not ideal, but could create a scatter plot method to deal with this.

```
let chart = Chart.Line [ for i in 0.0 .. 0.02 .. 2.0 * Math.PI -> (sin i, cos i * sin i) ]
chart.["chart_type"] <- "point"
chart
```

![screenshot from 2015-07-08 14 00 24](https://cloud.githubusercontent.com/assets/1476951/8579110/43ad6d4a-2578-11e5-9716-16d6ac5d85d5.png)

**Comment by mndrake** [comment]
I submitted an issue about the parametric plot issue (https://github.com/mozilla/metrics-graphics/issues/460)

**Comment by simra** [comment]
Everything works for me now, thanks!
Is there an easy way to get FAKE to do this step:
> %programdata%\jupyter\kernels\ifsharp\kernel.json

> with the content:

> { "display_name": "fsharp", "language": "fsharp", "argv": [ "C:\\Program Files\\BayardRock\\IFSharp\\ifsharp.exe", "{connection_file}" ] }

At a minimum it would be great to update the install doc in the branch with this info, but ideally a build generates kernel.json with the right path info.

**Comment by fradav** [comment]
@simra you say everything works for you : even intellisense tooltips?

**Comment by simra** [comment]
No, I didn't get that far- I was referring to my issue getting the kernel to load. Sorry for the confusion.

**Comment by mndrake** [comment]
@npmurphy Thanks for the help with the HMAC signature. The only thing I needed to tweak was adding a function to convert to a hex string. I updated my jupyter branch if anyone wants to try it. (https://github.com/mndrake/ifsharp/tree/jupyter)

```
        let toHexString (array:byte[]) =
            let hex = new StringBuilder(array.Length * 2)
            for b in array do
                hex.AppendFormat("{0:x2}", b) |> ignore
            hex.ToString()
```

I can now launch jupyter with just `ipython notebook` and swap between R/python/F# kernels without issue (at least in OS X).

**Comment by mndrake** [comment]
Most important feature yet! :laughing: I resized the F# logo so it shows up in the header when using the IfSharp kernel.

![ifsharp_logo](https://cloud.githubusercontent.com/assets/1476951/8986192/ab466752-36a0-11e5-9d13-06aae63eef0e.jpg)

**Comment by simra** [comment]
I investigated the intellisense issue.  In my case I had none of the custom .js files loading- I had to copy them to ~\.jupyter\custom
Now the custom js loads but in the process breaks the kernel loading process- I'm working on troubleshooting the js to see what's happening.

**Comment by simra** [comment]
Fyi I'm tracking a set of Jupyter/Intellisense issues here: https://github.com/simra/IfSharp/issues
Happy to move them to this project if we can get a jupyter branch running.

**Comment by cgravill** [comment]
There are some changes to the licensing of Plot.ly meaning it can run locally:
https://plot.ly/javascript/open-source-announcement/

It looks like the use of a local JavaScript is being added to XPlot currently:
https://github.com/TahaHachana/XPlot/commit/66fd9788bb1c9601e1841d82207d7302cf4b9b2d

**Comment by npmurphy** [comment]
In case people dont know, this branch works in Jupyter 4.0 on Windows and Linux. 
https://github.com/FilippoPolo/IfSharp

It also has intellisense working, provided you launch with `jupyter notebook --config ~/.local/share/jupyter/kernels/ifsharp/ipython_config.py`

**Comment by cgravill** [comment]
Lots of these fixes, suggestions, and improvements have been integrated from here into the Jupyter branch. We have intellisense working more predictably and support for the latest _Jupyter_ protocols.

I'm going to close this as I imagine that most people aren't interested in IPython 3.0 support now as it's superseded by Jupyter. For most people we have a working support for Jupyter. Please do open issues any current problems with the Jupyter branch and we'll try to sort them.
