### ISSUE TITLE
Display type of things

### ISSUE THREAD

**Issue by Quiark** [fsprojects/IfSharp#43]
Would it be possible to imlement showing the type of various parts of the code? For example the original F# interactive will display the type of anything that is not evaluated:

```
> Seq.find;;
val it : (('a -> bool) -> seq<'a> -> 'a) = <fun:clo@4-1>
```

ghci has the command `:t expr` to print the type of `expr`. Some IDE's display the type as a tooltip (that would need support selection so that you can choose what you want evaluated for type). 

Thanks :+1:

**Comment by cgravill** [comment]
I've merged in the change to the Jupyter branch so you can toggle in FSI output like this:

```
[1] Seq.find
```

no types, but you can then:

```
[2] #help;
Out[2]:
  IF# notebook directives:

    #fsioutput ["on"|"off"];;   Toggle output display on/off
    
  F# Interactive directives:

    #r "file.dll";;        Reference (dynamically load) the given DLL
    #I "path";;            Add the given search path for referenced DLLs
    #load "file.fs" ...;;  Load the given file(s) as if compiled and referenced
    #time ["on"|"off"];;   Toggle timing on/off
    #help;;                Display help
    #quit;;                Exit

  F# Interactive command line options:

      See 'ifsharp --help' for options
```

then

```
[3] #fsioutput "on"
    Seq.find
Out[3]:
val it : (('a -> bool) -> seq<'a> -> 'a)
```

Hope this helps!
