### ISSUE TITLE
Installation instructions OS X/Linux

### ISSUE THREAD

**Issue by haf** [fsprojects/IfSharp#45]
I tried to follow the [installation instructions](https://bayardrock.github.io/IfSharp/installation.html) but first got stuck because setup.exe isn't a cross-platform way of installation. Then when doing the manual installation, on step four, it asks me to open the iF# sln file, but there's no such file to open as a result of the previous commands. At least not one that I could find.

**Comment by cgravill** [comment]
We've added additional install instructions for Mac and Linux on the Jupyter branch. Please do try those out and raise any issues you experience.
