### ISSUE TITLE
how easy to extend IfSharp to other .NET languages?

### ISSUE THREAD

**Issue by denfromufa** [fsprojects/IfSharp#46]

**Comment by simra** [comment]
F# provides an interactive compilation facility (fsi.exe) that enables REPL loops.  I think the answer to your question depends on how hard it would be to create a REPL facility for, say, C#.  A quick search yields this mono project: http://www.mono-project.com/docs/tools+libraries/tools/repl/

**Comment by denfromufa** [comment]
i tried using icsharp but it is not working:

https://github.com/zabirauf/icsharp/issues/5

so how easy would it be to replace fsi.exe with scriptcs.exe?

mono REPL is probably more limited than scriptcs.

**Comment by denfromufa** [comment]
apparently there is F# for scriptcs:

https://github.com/scriptcs-contrib/scriptcs-fsharp

**Comment by cgravill** [comment]
There's newly released csi.exe that may be helpful this:
https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx#Csharp

Definitely makes more sense to do it in the icsharp project though.
