### ISSUE TITLE
How to install IF# kernel for Jupyter Notebook?

### ISSUE THREAD

**Issue by FabHan** [fsprojects/IfSharp#48]
Does IF# work with Jupyter Notebook? And how to install?

I use Linux, by the way.

**Comment by npmurphy** [comment]
Currently, this branch works very nicely on Linux and Jupyter 4.0
https://github.com/BayardRock/IfSharp/pull/47

Once you have compiled it, run the ifsharp.exe once to set up the config files. 
Then to use it run "jupyter notebook --config ~/.local/share/jupyter/kernels/ifsharp/ipython_config.py"

The paths are probably not set up properly so you have to add lines like 
#I "/usr/lib/cli/FSharp.Data.TypeProviders-4.3/"
#I "/path/to/ifsharp/IfSharp/bin"
#r "IfSharp.Kernel.dll"
to each notebook or fsx file.

The built in plotting doesn't work, you have to use a more uptodate version of FSLab.

**Comment by cgravill** [comment]
@npmurphy added documentation on the Jupyter branch here: https://github.com/fsprojects/IfSharp/tree/jupyter

I'm going to go ahead and close this, please do raise any issues you have with this or improvements to the documentation.
