### ISSUE TITLE
Maintainer status?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/IfSharp#50]
Hi @Rickasaurus @prosconi , 

Would you like to bring on more maintainers to this project?  I suspect we could recruit more maintainers via twitter?

Best
Don

**Comment by prosconi** [comment]
I agree, I don't really have time lately to keep this up-to-date.

- Peter

**Comment by dsyme** [comment]
Would you want to keep it here (is Bayard happy with a non-Bayard maintainer?) or move it to fsprojects or ...?

**Comment by prosconi** [comment]
I'm fine with moving it, will confer with @Rickasaurus

**Comment by prosconi** [comment]
@Rickasaurus concurs, how do we move this thing to fsprojects?

**Comment by dsyme** [comment]
You should now have invitations to "fsprojects".  I think you can then just press "transfer project" under the project settings.  We can then fix up the privileges and start recruiting additional maintainers (hopefully1).  You'll need to be co-maintainers for a good while to help onboard.

Are there any other Bayard projects you'd like to move?

**Comment by kevmal** [comment]
I'm currently getting FsBeaker up to date. Once I'm finished with most of the common auto-translations I'll submit a PR. Perhaps another candidate for fsprojects?

**Comment by prosconi** [comment]
@kevmal I agree, FsBeaker is a good candidate also

**Comment by prosconi** [comment]
Transferred.

**Comment by dsyme** [comment]
I've added @prosconi and @Rickasaurus as owners.  

I've also added @cgravill who is willing to be a repo facilitator too.

**Comment by cgravill** [comment]
Thanks for migrating the project and all your work so far - it's been really useful having F# support in the notebook system.

I've opened a branch for Jupyter support as that seems like the major issue currently. There's a pull request from @FilippoPolo #51 adds support for Jupyter and several other features. I can see from the other forks that people have added useful features as well - @mndrake @simra and others - it would be great to get these merged to a central location on fsprojects. I'll try to coordinate these efforts if people make pull requests.

Discussed with @Rickasaurus and the intention is to make a branch of the current master for anyone who needs IPython 1.X or 2.X then move master onto Jupyter.

**Comment by simra** [comment]
Great to see all the progress with Jupyter and FSProjects.  I don't think my changes add anything beyond what @FilippoPolo has contributed.  I'll likely set up a new fork integrating his PR and work from there, and I'll circle back if I have anything to add.

**Comment by sylvanc** [comment]
Closing as this has moved to fsprojects.
