### ISSUE TITLE
Proposal: Dockerfile for Jupyter - Linux 

### ISSUE THREAD

**Issue by luminescent** [fsprojects/IfSharp#62]
Hello 

Let me start by saying thank you for the wonderful effort put into building the F#  kernel for Jupyter, it is a great and useful piece of work, especially on Linux where the tooling around this language is not as well developed as on Windows. 

In my efforts to streamline my work I built a Dockerfile for getting started immediately with Jupyter F#. It is based on Anaconda3 and accepts connections from everyone on 8888. The notebooks get saved in a volume that can be mounted on running the image. 
I'm guessing it could be useful for people who want to quickly take a look at how it works and don't want to install everything locally (by everything I mean Anaconda, Jupyter and mono), or update their already configured environment to support the versions we need for running the F# kernel.  

I could bring the Docker file into this repo, if there's any interest in it. Currently I have it [here](https://github.com/luminescent/docker_images/tree/master/jupyter_ifsharp) along with a more elaborate explanation of how to use it. 

Off the top of my head there are a few things I could tweak: 
- base it on something smaller than Anaconda3 (though my initial attempts to use `minimal-notebook` - the official image, have failed)
- stop hard-coding allowed IP addresses and just pass the arguments to `jupyter-notebook` via the `docker run`
- perhaps not clone the IfSharp repo inside the image (once built, re-building the image will not pull newer versions of the code because of the Docker cache), however not sure how to checkout a branch using the Docker context
- etc

Please do let me know if you think it would benefit the project and I'll work on it a bit more. 
Thank you.

**Comment by cgravill** [comment]
That sounds like a really useful thing to have available. Much easier for people to install in a no impact fashion.

I haven't authored any docker containers myself so I don't know about expectations on updates. It would be great if people are able to update their IfSharp without having to clean their Docker cache.

Presumably it's pretty big with a full Anaconda3 install?

**Comment by luminescent** [comment]
Hi 

Great :). I now have a version that's based on a mono image with python added and then Jupyter installed via pip install; it does not have any of the extra goodies Anaconda brings in, so it's smaller (though Python by itself alone is quite sizable). I am working on another one based on Alpine, which will be even smaller - might have something working around next week (Alpine is experimental, but when it works, it's great :)). 

I'll work on the updates being picked up even when caching is on. It's a simple problem when we're not working with git branches, I have to see if Docker allows me to switch branches when the  context is a git folder (just a matter of trying it out, just have not gotten around to doing it). 

With Docker images, a better practice is to use the Github releases rather than building IfSharp from source inside the image, so I'll try that as well, again I have not tested if running `mono setup.exe` is enough to have things running on Debian (I presume it does the same thing `mono ifsharp.exe` does). If that works, then the updates issue does not exist anymore and we could just publish it on the Docker hub, labeled with the release version, and people could just issue this command and have everything running: 

`docker run -d -p 8888:8888 jupyter_ifsharp:2.0.2-Beta`

**Comment by luminescent** [comment]
Took a second look at things and looks like we need a release to go around the caching thing. 

Is it possible to make a release out of the jupyter branch? I could do it or help with testing if someone walks me through how it's done. 

Thank you.

**Comment by cgravill** [comment]
We should be able to do an alpha release. I've not done a release before but will look into it. There's a related request for installers which we may have a reached stable enough point with Jupyter for.

Thanks for the progress so far, it's looking promising.

**Comment by cgravill** [comment]
I've created a test release here:
https://github.com/fsprojects/IfSharp/releases/tag/v3.0.0-alpha1

I did a build on Windows and included that. For Docker do you need binaries or source code then build yourself?

Let me know how it goes and if any changes would help.

**Comment by luminescent** [comment]
Thank you, great news. I'm going to give it a go with the binaries, the ones built on Windows should work fine. I'll reply how it went in a bit.

**Comment by luminescent** [comment]
Hi 

I have added the Docker file and updated the readme file on my fork (it's currently for the jupyter branch only). The readme details how to build and run the container. Internally the binaries from the release are used. 
How should I proceed, do I submit a PR for adding the Docker file to the repository? 
At some point I will look into publishing it on the [Docker hub](https://hub.docker.com/explore/), so people won't have to clone the repository on their end, though I'll need a bit of time to see how the hub deals with branches.

**Comment by cgravill** [comment]
It definitely makes sense to merge in the instructions for using the dockerfile. I haven't used Docker much so happy to be guided by you and we can see how it goes. I have the Windows and OS X Docker beta tools installed now so I'm happy to test if that would help?

Would the script do the build of IfSharp then build the docker image from that?

**Comment by luminescent** [comment]
Sure; I think the easiest is to pull my fork, checkout the jupyter branch, then follow the instructions from the readme - this way we can also check if they're good enough. If you encounter issues I'll update the readme and the file accordingly. If all goes smoothly, I've submitted the PR with the changes and you could merge it in. 

Since you're on OS X you'll have to use the IP address of the docker machine rather than localhost (you'll see what I mean once you get to that step). 

The [Dockerfile](https://github.com/luminescent/IfSharp/blob/jupyter/Dockerfile) uses the already built binaries from the release you published a little while ago, 3.0.0-alpha1. Initially I had it building from the source, but I was running into that Docker caching issue - rebuilding the image with the same url would use the sources from the Docker cache rather than pulling the latest from Github.

**Comment by cgravill** [comment]
I've just updated the docker file to the alpha2 release (has some stability fixes) and wanted to test this out. I tried running the build command, which ran to completion (with plenty of red), then was able to launch the docker container

```
docker build -t ifsharp:3.0.0-alpha .
docker run -d -v ~/notebooks:/notebooks -p 8889:8888 ifsharp:3.0.0-alpha
```

It comes up fine and I'm able to connect and even create notebooks. However, the F# hangs on sending a command. I tried with the Python as a reference test, and it errors with:

`The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.`

It's writing to my ~/notebooks directory and the shell.log is created without errors on the F# part
[shell.log.txt](https://github.com/fsprojects/IfSharp/files/449490/shell.log.txt)

I'm running on OSX, Docker for Mac
Version 1.12.0-a (build: 11213)
ad6ab836187e4111082447b7c0a6a74d01929a5c

I can try this on a Windows machine too. Any clues how to investigate? I'm not that experienced with Docker still.

**Comment by luminescent** [comment]
Hi Colin

This should not happen... I will take a look ASAP. Theoretically you will
have the same issues if you launch it in Docker on Windows.

Just to clarify, you can create F# notebooks, but you cannot run a cell,
can you? I.e., once you press the "run cell" button, it never terminates?

Thank you.

**Comment by cgravill** [comment]
Thanks, much appreciated. It might be specific to my set-up but it would be great to have a confirmation how it's behaving for you.

Yes, exactly, I can create F# notebooks (and Python notebooks). When I do a "run cell" on an F# notebook it stars the cell indicating a computation is in progress but never completes.

I'm guessing the Python notebook failure may be helpful in diagnosing what's wrong

**Comment by sylvanc** [comment]
Closing as we now have an updated and simplified Dockerfile that builds from the repo.
