### ISSUE TITLE
no mouse-over type signatures

### ISSUE THREAD

**Issue by jaredtkatz** [fsprojects/IfSharp#63]
### Description

I don't see any examples of mouse-over type signatures in the README or Feature Notebook, so I'm not sure if I screwed up the installation or if they are not implemented. 

### Repro steps

Please provide the steps required to reproduce the problem

1. Clean install of IFSharp on Windows 10

2. Mouse-over assigned value

### Expected behavior

I expect to see a tooltip pop-up with the value's type signature as I would in Visual Studio

### Actual behavior

Nothing happens

### Related information 

* Windows 10
* IFSharp v2.0.2-Beta

**Comment by cgravill** [comment]
I don't think this has been implemented so far. There is completion.

Someone could implement such a system, potentially using something like https://github.com/tpetricek/FSharp.Formatting

**Comment by jaredtkatz** [comment]
Does anyone know if there's an easy way to determine the type sig of a function without the mouse-over feature? Is there a higher order function that can return the type sig?

**Comment by cgravill** [comment]
If you just want the type signatures and are willing to alter the source of IfSharp you can dump the FSI output.

Add:`pyout (sbOut.ToString())`

just after:

```fsharp
        if not <| String.IsNullOrEmpty(newCode) then
            fsiEval.EvalInteraction(newCode)
```

and comment out

```fsharp
                if data.Count = 0 then
```

Adding an option to return this could be useful more generally.

Demo:
![image](https://cloud.githubusercontent.com/assets/1099725/15082611/8edc8f4e-13c0-11e6-8933-c77126fda366.png)

**Comment by cgravill** [comment]
Similar feature request in #43

**Comment by Rickasaurus** [comment]
Perhaps this could be done in a similar way to FSI pragmas? For example #typeinfo to toggle that.

**Comment by cgravill** [comment]
A toggle for detailed information makes sense to me. I was thinking something equivalent to #time ["on"|"off"] would be useful.

@Rickasaurus do you know what the reasoning behind:
```fsharp
if data.Count = 0 then
```
It seemed a bit strange if you #N a nuget and later in the cell have an expression then it only gives the #N outputs. I thought about removing the check but wondering if it's dealing with other issues?

**Comment by prosconi** [comment]
@cgravill as far as I can tell the "data" variable was previously being used to queue up things to send to the client and then send them. I am pretty sure it can be removed altogether

**Comment by cgravill** [comment]
Thanks for the clarification. I'll try removing "data" and see if anything bad happens.

**Comment by cgravill** [comment]
I've merged in the change to the Jupyter branch so you can toggle in FSI output like this:

```
In [1]:

  #fsioutput "on"
​
  let x = 2
  x

Out[1]:

  val x : int = 2
  val it : int = 2

Out[1]:

  2
```

Any opinions if this is sufficient or we'd still want mouse hovering?

**Comment by Rickasaurus** [comment]
Of course hovering would be awesome! I'm not sure what levers are available in Jupyter to do that though.

**Comment by sylvanc** [comment]
Closing as hover support doesn't appear to be available in Jupyter, and @cgravill 's `#fsioutput` gives type information.

**Comment by jgoode** [comment]
#fsioutput does not work in current implementation
