### ISSUE TITLE
NetMQ version upgrade breaks on Linux/Mono

### ISSUE THREAD

**Issue by npmurphy** [fsprojects/IfSharp#68]
Since the upgrade from NetMQ 3.0.11 to 3.3.2, Jupyter cannot connect or send commands to IfSharp kernel on Mono 4.4. 

In the file "Kernel.fs" the debugger seems to lose the connection in
the `socket.ReceiveMultipartBytes()` function.
It runs the line  `let recvAll (socket: NetMQSocket) = socket.ReceiveMultipartBytes()` twice and then the process stops talking with the debugger.
I added some printf statements before and after the call to `ReceiveMultipartBytes`, only the "before" message is printed, twice. These seem to be control messages.  

So it looks like two control messages are received but then socket.ReceiveMultipartBytes is waiting forever.

Perhaps this zeromq/netmq#553 is related.

### Related information 

* Operating system: Ubuntu 15.10
* Mono Version: (Stable 4.4.0.142/81f38a9)

**Comment by cgravill** [comment]
Where is the Mono version sourced from? It says stable but to my understanding 4.4.* isn't released yet:

"The latest Mono release is: 4.2 SR2 (4.2.3.4)"
http://www.mono-project.com/download/

**Comment by npmurphy** [comment]
You are right, downgrading to 4.2 fixes it. 
Sorry, I forgot that I had switched to a beta channel.
