### ISSUE TITLE
IfSharp Kernel will not start correctly in Jupyter

### ISSUE THREAD

**Issue by fusi123** [fsprojects/IfSharp#76]
### Description

Unable to use the IFSharp kernel in Jupyter notebook. When choosing a IFSharp notebook the window opens but the kernel does not start successfully.

### Repro steps

Open a new IFSharp notebook.
IfSharpConsole immediately crashes. Attached file is shown in console window.
[ifsharperr.txt](https://github.com/fsprojects/IfSharp/files/317660/ifsharperr.txt)

### Related information 

Windows 8.1 64 bit
IfSharp v3.0.0-alpha1
Jupyter Notebook Version 4.1.0
Python 3.5.1
Anaconda 4.0.0

**Comment by cgravill** [comment]
It looks like there is a problem starting the fsi instance that we use to process F# code.

Does the machine have an installation of Visual Studio on it? If so is it able to start an F# interactive window successfully?

**Comment by fusi123** [comment]
I have 2012 Premium installed. I can open F# interactive without any issues inside VS.

**Comment by Rickasaurus** [comment]
It sounds like a pathing issue. Could try try installing the latest redist? https://www.microsoft.com/en-us/download/details.aspx?id=48179

**Comment by sylvanc** [comment]
Closing because the issue is stale. If you have problems with the current build, please do open another issue :)
