### ISSUE TITLE
IFSharp seems working in x86 mode

### ISSUE THREAD

**Issue by sihel** [fsprojects/IfSharp#79]
### Description

I installed the latest version and tried to launch the simpliest code which demands using an external library.
The problem is that this library works perfectly in x64 mode only. So, in IFSharp I am experiencing the same problem as in F# Interactive in x86 mode. 
When I met it in F# Interactive I figured out that the only problem is x86 mode and if I change it in VS settings, everything works properly.  Therefore, at the moment it seems that IFSharp works in x86 mode and I cannot change it in the settings.
Could you please look how it is possible and how to launch it in right mode?

**Comment by cgravill** [comment]
Generally IfSharp is running in 64bit/x64 mode. The documentation actually suggests it only works in x64. I tried installing from the IfSharp.v3.0.0-alpha1.zip and direct from source. Then with a test notebook and the snippet `System.IntPtr.Size` it gave 8. Do you get the same?

There might be other issues, the fsi process in IfSharp is doing a few things to let us capture output. What error do you see with your library?

**Comment by sihel** [comment]
It is strange, but I really see 4 instead of 8. So I guess I launched it in x86 mode somehow. How could I change it?

What about my library, it is just an internal error about incomparable formats. As I mentioned, this errors occur when I try to use the library in x86 mode.

**Comment by cgravill** [comment]
That's curious! How are you running it? Direct from source control or the zip download?

Are you running a 32bit or 64bit version of Python?

Mine:
```
> python -V
Python 3.5.1 :: Anacoda 4.1.0 (64-bit)
```

**Comment by sihel** [comment]
I downloaded zip (IfSharp.v3.0.0-alpha1.zip) and installed by launching ifsharp.exe (as I remmember).

But the difference is that I did not install Anaconda before IPython. Could it be crucial?
My Python version is:

```
> python -V
Python 2.7.11 --  64-bit
```

**Comment by cgravill** [comment]
I'm not sure. I don't actually know how to make IfSharp work in 32bit mode - it's compiled entirely for 64bit throughout!

To check I ran the corflags.exe tool on ifsharp.exe

```
E:\dev\IfSharp\bin>corflags ifsharp.exe
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.6.1055.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32+
CorFlags  : 0x1
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 0
```

neither of the 32bit flags are set to 0 (true) so it ought not to run as 32bit. I don't get how yours is!

You do have a fairly old version of Python, perhaps there's a old version IPython/Jupyter that forces 32bit processes somehow? You could try wiping Python/Jupyter/IfSharp and starting from a clean state.

**Comment by Rickasaurus** [comment]
If I remember right, I think we made the original version 64-bit only to simplify the zmq dependency.

**Comment by cgravill** [comment]
@Rickasaurus sounds reasonable, and I'm fine with continuing to mandate 64-bit for simplicity.

Do you have any idea how it's managing to run in 32-bit? I would have guessed that's impossible, short of modifying ifsharp.exe, but the pointer size test above seems to confirm it's running 32-bit.

**Comment by sylvanc** [comment]
Closing as the issue is stale. If you have problems with the current build, please do open another issue :)
