### ISSUE TITLE
How do I output to the ipython console from ifsharp source. 

### ISSUE THREAD

**Issue by mattroid** [fsprojects/IfSharp#81]
I'm trying to change the sources of the nuget repo and it doesn't appear to be using the ifsharp.exe.config?

I add my repo url to the ifsharp.exe.config, the %home%/.nuget/NuGet.config, the %AppData%/NuGet/NuGet.config. Still can't find my custom packages.

I tried to output the source on NugetManager.fs:161 but it doesn't show in the output of the running ipyhon.exe. 
I tried Console.Writeline
I tried source |> Display

Not sure how to print debug info from the Kernal project?

**Comment by cgravill** [comment]
The console you're seeing is from the Python process running Jupyter. I don't think we've writing to that anywhere yet.

What's been done elsewhere is writing to a shell.log file. There's a function in kernel.fs that does this: `let logMessage (msg : string)`.

If you want something quick, you copy that into NugetManager.fs. We might want to move this logging functionality higher in the compilation order.

**Comment by cgravill** [comment]
Related it's actually possible to attach a debugger if that helps. Jupyter "back launches" the ifsharp.exe process but you can then use Visual Studio to "debug > Attach to process..."

**Comment by cgravill** [comment]
Actually, I've found that console output does pass through for me e.g.

```fsharp
    /// Preprocesses the specified source string
    member this.Preprocess (source : string) =

        Console.Out.WriteLine("Test in IFSharp")
```
results in this:

![image](https://cloud.githubusercontent.com/assets/1099725/18050363/0d297ee6-6de6-11e6-9118-724d00e84768.png)

Are you sure you've got the IFSharp.exe rebuilt and running?

**Comment by sylvanc** [comment]
Closing as the issue is stale. If you have problems with the current build, please do open another issue :)
