### ISSUE TITLE
Error On Trying to Chart

### ISSUE THREAD

**Issue by angrydexterous** [fsprojects/IfSharp#83]
### Description

Ran latest docker repo, and ran latest from source -> following error occurs in both when running charting from the demos

> System.ArgumentNullException: Value cannot be null.
> Parameter name: key
>   at System.ThrowHelper.ThrowArgumentNullException (ExceptionArgument argument) <0x7f92825f65d0 + 0x00021> in <filename unknown>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (System.Collections.Generic.TKey key) <0x409fb690 + 0x00033> in <filename unknown>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (System.Collections.Generic.TKey key) <0x409fb640 + 0x00019> in <filename unknown>:0 
>   at FSharp.Charting.ChartTypes.layoutSubCharts@798 (SeriesChartType chartType, System.Collections.Generic.Dictionary`2 visited, Microsoft.FSharp.Core.FSharpOption`1 targetParent, System.Object target) <0x409fb160 + 0x0004d> in <filename unknown>:0 
>   at FSharp.Charting.ChartTypes.layoutSubCharts@798 (SeriesChartType chartType, System.Collections.Generic.Dictionary`2 visited, Microsoft.FSharp.Core.FSharpOption`1 targetParent, System.Object target) <0x409fb160 + 0x002ff> in <filename unknown>:0 
>   at FSharp.Charting.ChartTypes+layoutSubCharts@798-1.Invoke (Microsoft.FSharp.Core.FSharpOption`1 targetParent, System.Object target) <0x409fb110 + 0x0002b> in <filename unknown>:0 
>   at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3252[T2,TResult,T1].Invoke (T2 u) <0x403bdda0 + 0x00029> in <filename unknown>:0 
>   at FSharp.Charting.ChartTypes+applyPropertyDefaults@810-1[a].Invoke (a arg10) <0x409fb0e0 + 0x00021> in <filename unknown>:0 
>   at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2 func, Microsoft.FSharp.Core.T arg1, Microsoft.FSharp.Core.TResult arg2) <0x4039d110 + 0x000a5> in <filename unknown>:0 
>   at FSharp.Charting.ChartTypes.applyPropertyDefaults[a] (SeriesChartType chartType, FSharp.Charting.a target) <0x409fac00 + 0x00187> in <filename unknown>:0 
>   at FSharp.Charting.ChartTypes+GenericChart..ctor (SeriesChartType chartType) <0x409fa420 + 0x00187> in <filename unknown>:0 
>   at FSharp.Charting.Chart.Line[a97,a98,a99] (IEnumerable`1 data, Microsoft.FSharp.Core.FSharpOption`1 Name, Microsoft.FSharp.Core.FSharpOption`1 Title, Microsoft.FSharp.Core.FSharpOption`1 Labels, Microsoft.FSharp.Core.FSharpOption`1 Color, Microsoft.FSharp.Core.FSharpOption`1 XTitle, Microsoft.FSharp.Core.FSharpOption`1 YTitle) <0x409ef440 + 0x0005f> in <filename unknown>:0 
>   at <StartupCode$FSI_0005>.$FSI_0005.main@ () <0x409fef00 + 0x0028b> in <filename unknown>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7f92826ef2f0 + 0x000a1> in <filename unknown>:0 
> Stopped due to error

### Repro steps

> open System
> open FSharp.Charting
> 
> // start at -PI and finish at PI
> let startX = -Math.PI
> let endX = Math.PI
> 
> // the data
> let data = 
>     [| startX..0.1..endX |]
>     |> Array.map (fun x -> (x, sin(x)))
> 
> // display a line graph
> Chart.Line(data)
> |> Chart.WithXAxis(true, "", 3.2, -3.2)
> |> Chart.WithYAxis(true, "", 1.0, -1.0)
> |> Display
> 
> // display the latex
> Util.Math("f(x) = sin(x)") |> Display
> 

### Expected behavior

No Error

### Actual behavior

Error shown above

### Known workarounds

No workaround

### Related information 

* Operating system - Docker image, and native Ubuntu 15.06
* Branch - latest
* Mono 4.4.2
* Performance information, links to performance testing scripts

**Comment by cgravill** [comment]
Is the "latest" branch the "jupyter" branch?

We've been trying to improve charting, for both Windows and Mono on Linux and Mac. This is quite new and not documented yet but you can see some details in #65. It looks like @npmurphy was able to get charting working on Ubuntu. I think that's running native rather than under Docker.

Related, is a clean checkout building the Docker image for you? I currently have issues building that on Mac, see #62

**Comment by npmurphy** [comment]
The current version of FSCharting.GTK does not work "out of the box". 
There are ways to get it working but I do not recommend using FSCharting.GTK unless you have the time to implement the missing parts of the library yourself. It is quite incomplete. 

I recommend XPlot.Plotly for plotting instead. 

If you really need FSCharting.GTK to work I can tell you some of the changes that need to be made to the FSCharting source. 
The solution I found depends on changing FSCharting.GTK dependency to a particular unstable version of OxyPlot "1.0.0-unstable2100" which has the function to make a bitmap but before the API changes were introduced.

**Comment by sylvanc** [comment]
The current jupyter branch has cross-platform charting via `XPlot.Plotly` and `Angara.Chart`.
